name: Sync from Org Repo to Personal Repo

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Org Repository
      - name: Checkout Org Repo
        uses: actions/checkout@v3
        with:
          repository: keyom-ai/aigurupro
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main

      # Step 2: Add Personal Repository as a Remote
      - name: Add Personal Repo Remote
        run: |
          git remote add personal https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/desirit/aigurupro.git
          git remote -v

      # Step 3: Sync Org Repo to Personal Repo
      - name: Push to Personal Repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase
          git push personal main --force
